version: 2

jobs:
 deploy:
   docker:
     - image: anmcarrow/ssh-client:latest
   resource_class: small
   steps:
     - run:
         name: Deploy Over SSH
         command: |
           ssh -o StrictHostKeyChecking=no -t $SSH_USER@$SSH_HOST "docker exec -ti awkng_srd /mkdocs/update.sh"

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
