version: 2

jobs:
 deploy:
   machine:
     enabled: true
   steps:
     - run:
         name: Deploy Over SSH
         command: |
           ssh -t $SSH_USER@$SSH_HOST "docker exec -ti awkng_srd /mkdocs/update.sh"

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
